// default package
// Generated 13-feb-2015 13.52.38 by Hibernate Tools 3.4.0.CR1
package main.webapp.ecsa.hibernate;
import java.util.Date;

/**
 * Languages generated by hbm2java
 */
public class Languages implements java.io.Serializable {

	private Integer id;
	private String abbreviation;
	private String name;
	private boolean enabled;
	private Date mirrorupdate;
	private String englishname;

	public Languages() {
	}

	public Languages(String abbreviation, String name, boolean enabled,
			Date mirrorupdate, String englishname) {
		this.abbreviation = abbreviation;
		this.name = name;
		this.enabled = enabled;
		this.mirrorupdate = mirrorupdate;
		this.englishname = englishname;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Date getMirrorupdate() {
		return this.mirrorupdate;
	}

	public void setMirrorupdate(Date mirrorupdate) {
		this.mirrorupdate = mirrorupdate;
	}

	public String getEnglishname() {
		return this.englishname;
	}

	public void setEnglishname(String englishname) {
		this.englishname = englishname;
	}

}
