// default package
// Generated 13-feb-2015 13.52.38 by Hibernate Tools 3.4.0.CR1
package main.webapp.ecsa.hibernate;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Tvepisodes generated by hbm2java
 */
public class Tvepisodes implements java.io.Serializable {

	private Integer id;
	private int seasonid;
	private int episodeNumber;
	private String episodeName;
	private String firstAired;
	private String guestStars;
	private String director;
	private String writer;
	private String overview;
	private String productionCode;
	private String showUrl;
	private Integer lastupdated;
	private Integer flagged;
	private String dvdDiscid;
	private Integer dvdSeason;
	private BigDecimal dvdEpisodenumber;
	private Integer dvdChapter;
	private String locked;
	private Integer absoluteNumber;
	private String filename;
	private int seriesid;
	private int lastupdatedby;
	private String airsafterSeason;
	private Integer airsbeforeSeason;
	private Integer airsbeforeEpisode;
	private int thumbAuthor;
	private Date thumbAdded;
	private Short thumbWidth;
	private Short thumbHeight;
	private Long tmsExport;
	private Date mirrorupdate;
	private int lockedby;
	private String imdbId;
	private Byte epImgFlag;
	private Integer tmsReviewBy;
	private Date tmsReviewDate;
	private boolean tmsReviewBlurry;
	private boolean tmsReviewDark;
	private boolean tmsReviewLogo;
	private boolean tmsReviewOther;
	private boolean tmsReviewUnsure;
	private boolean tmsPriority;

	public Tvepisodes() {
	}

	public Tvepisodes(int seasonid, int episodeNumber, String locked,
			int seriesid, int lastupdatedby, int thumbAuthor,
			Date mirrorupdate, int lockedby, boolean tmsReviewBlurry,
			boolean tmsReviewDark, boolean tmsReviewLogo,
			boolean tmsReviewOther, boolean tmsReviewUnsure, boolean tmsPriority) {
		this.seasonid = seasonid;
		this.episodeNumber = episodeNumber;
		this.locked = locked;
		this.seriesid = seriesid;
		this.lastupdatedby = lastupdatedby;
		this.thumbAuthor = thumbAuthor;
		this.mirrorupdate = mirrorupdate;
		this.lockedby = lockedby;
		this.tmsReviewBlurry = tmsReviewBlurry;
		this.tmsReviewDark = tmsReviewDark;
		this.tmsReviewLogo = tmsReviewLogo;
		this.tmsReviewOther = tmsReviewOther;
		this.tmsReviewUnsure = tmsReviewUnsure;
		this.tmsPriority = tmsPriority;
	}

	public Tvepisodes(int seasonid, int episodeNumber, String episodeName,
			String firstAired, String guestStars, String director,
			String writer, String overview, String productionCode,
			String showUrl, Integer lastupdated, Integer flagged,
			String dvdDiscid, Integer dvdSeason, BigDecimal dvdEpisodenumber,
			Integer dvdChapter, String locked, Integer absoluteNumber,
			String filename, int seriesid, int lastupdatedby,
			String airsafterSeason, Integer airsbeforeSeason,
			Integer airsbeforeEpisode, int thumbAuthor, Date thumbAdded,
			Short thumbWidth, Short thumbHeight, Long tmsExport,
			Date mirrorupdate, int lockedby, String imdbId, Byte epImgFlag,
			Integer tmsReviewBy, Date tmsReviewDate, boolean tmsReviewBlurry,
			boolean tmsReviewDark, boolean tmsReviewLogo,
			boolean tmsReviewOther, boolean tmsReviewUnsure, boolean tmsPriority) {
		this.seasonid = seasonid;
		this.episodeNumber = episodeNumber;
		this.episodeName = episodeName;
		this.firstAired = firstAired;
		this.guestStars = guestStars;
		this.director = director;
		this.writer = writer;
		this.overview = overview;
		this.productionCode = productionCode;
		this.showUrl = showUrl;
		this.lastupdated = lastupdated;
		this.flagged = flagged;
		this.dvdDiscid = dvdDiscid;
		this.dvdSeason = dvdSeason;
		this.dvdEpisodenumber = dvdEpisodenumber;
		this.dvdChapter = dvdChapter;
		this.locked = locked;
		this.absoluteNumber = absoluteNumber;
		this.filename = filename;
		this.seriesid = seriesid;
		this.lastupdatedby = lastupdatedby;
		this.airsafterSeason = airsafterSeason;
		this.airsbeforeSeason = airsbeforeSeason;
		this.airsbeforeEpisode = airsbeforeEpisode;
		this.thumbAuthor = thumbAuthor;
		this.thumbAdded = thumbAdded;
		this.thumbWidth = thumbWidth;
		this.thumbHeight = thumbHeight;
		this.tmsExport = tmsExport;
		this.mirrorupdate = mirrorupdate;
		this.lockedby = lockedby;
		this.imdbId = imdbId;
		this.epImgFlag = epImgFlag;
		this.tmsReviewBy = tmsReviewBy;
		this.tmsReviewDate = tmsReviewDate;
		this.tmsReviewBlurry = tmsReviewBlurry;
		this.tmsReviewDark = tmsReviewDark;
		this.tmsReviewLogo = tmsReviewLogo;
		this.tmsReviewOther = tmsReviewOther;
		this.tmsReviewUnsure = tmsReviewUnsure;
		this.tmsPriority = tmsPriority;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getSeasonid() {
		return this.seasonid;
	}

	public void setSeasonid(int seasonid) {
		this.seasonid = seasonid;
	}

	public int getEpisodeNumber() {
		return this.episodeNumber;
	}

	public void setEpisodeNumber(int episodeNumber) {
		this.episodeNumber = episodeNumber;
	}

	public String getEpisodeName() {
		return this.episodeName;
	}

	public void setEpisodeName(String episodeName) {
		this.episodeName = episodeName;
	}

	public String getFirstAired() {
		return this.firstAired;
	}

	public void setFirstAired(String firstAired) {
		this.firstAired = firstAired;
	}

	public String getGuestStars() {
		return this.guestStars;
	}

	public void setGuestStars(String guestStars) {
		this.guestStars = guestStars;
	}

	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public String getWriter() {
		return this.writer;
	}

	public void setWriter(String writer) {
		this.writer = writer;
	}

	public String getOverview() {
		return this.overview;
	}

	public void setOverview(String overview) {
		this.overview = overview;
	}

	public String getProductionCode() {
		return this.productionCode;
	}

	public void setProductionCode(String productionCode) {
		this.productionCode = productionCode;
	}

	public String getShowUrl() {
		return this.showUrl;
	}

	public void setShowUrl(String showUrl) {
		this.showUrl = showUrl;
	}

	public Integer getLastupdated() {
		return this.lastupdated;
	}

	public void setLastupdated(Integer lastupdated) {
		this.lastupdated = lastupdated;
	}

	public Integer getFlagged() {
		return this.flagged;
	}

	public void setFlagged(Integer flagged) {
		this.flagged = flagged;
	}

	public String getDvdDiscid() {
		return this.dvdDiscid;
	}

	public void setDvdDiscid(String dvdDiscid) {
		this.dvdDiscid = dvdDiscid;
	}

	public Integer getDvdSeason() {
		return this.dvdSeason;
	}

	public void setDvdSeason(Integer dvdSeason) {
		this.dvdSeason = dvdSeason;
	}

	public BigDecimal getDvdEpisodenumber() {
		return this.dvdEpisodenumber;
	}

	public void setDvdEpisodenumber(BigDecimal dvdEpisodenumber) {
		this.dvdEpisodenumber = dvdEpisodenumber;
	}

	public Integer getDvdChapter() {
		return this.dvdChapter;
	}

	public void setDvdChapter(Integer dvdChapter) {
		this.dvdChapter = dvdChapter;
	}

	public String getLocked() {
		return this.locked;
	}

	public void setLocked(String locked) {
		this.locked = locked;
	}

	public Integer getAbsoluteNumber() {
		return this.absoluteNumber;
	}

	public void setAbsoluteNumber(Integer absoluteNumber) {
		this.absoluteNumber = absoluteNumber;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public int getSeriesid() {
		return this.seriesid;
	}

	public void setSeriesid(int seriesid) {
		this.seriesid = seriesid;
	}

	public int getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(int lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	public String getAirsafterSeason() {
		return this.airsafterSeason;
	}

	public void setAirsafterSeason(String airsafterSeason) {
		this.airsafterSeason = airsafterSeason;
	}

	public Integer getAirsbeforeSeason() {
		return this.airsbeforeSeason;
	}

	public void setAirsbeforeSeason(Integer airsbeforeSeason) {
		this.airsbeforeSeason = airsbeforeSeason;
	}

	public Integer getAirsbeforeEpisode() {
		return this.airsbeforeEpisode;
	}

	public void setAirsbeforeEpisode(Integer airsbeforeEpisode) {
		this.airsbeforeEpisode = airsbeforeEpisode;
	}

	public int getThumbAuthor() {
		return this.thumbAuthor;
	}

	public void setThumbAuthor(int thumbAuthor) {
		this.thumbAuthor = thumbAuthor;
	}

	public Date getThumbAdded() {
		return this.thumbAdded;
	}

	public void setThumbAdded(Date thumbAdded) {
		this.thumbAdded = thumbAdded;
	}

	public Short getThumbWidth() {
		return this.thumbWidth;
	}

	public void setThumbWidth(Short thumbWidth) {
		this.thumbWidth = thumbWidth;
	}

	public Short getThumbHeight() {
		return this.thumbHeight;
	}

	public void setThumbHeight(Short thumbHeight) {
		this.thumbHeight = thumbHeight;
	}

	public Long getTmsExport() {
		return this.tmsExport;
	}

	public void setTmsExport(Long tmsExport) {
		this.tmsExport = tmsExport;
	}

	public Date getMirrorupdate() {
		return this.mirrorupdate;
	}

	public void setMirrorupdate(Date mirrorupdate) {
		this.mirrorupdate = mirrorupdate;
	}

	public int getLockedby() {
		return this.lockedby;
	}

	public void setLockedby(int lockedby) {
		this.lockedby = lockedby;
	}

	public String getImdbId() {
		return this.imdbId;
	}

	public void setImdbId(String imdbId) {
		this.imdbId = imdbId;
	}

	public Byte getEpImgFlag() {
		return this.epImgFlag;
	}

	public void setEpImgFlag(Byte epImgFlag) {
		this.epImgFlag = epImgFlag;
	}

	public Integer getTmsReviewBy() {
		return this.tmsReviewBy;
	}

	public void setTmsReviewBy(Integer tmsReviewBy) {
		this.tmsReviewBy = tmsReviewBy;
	}

	public Date getTmsReviewDate() {
		return this.tmsReviewDate;
	}

	public void setTmsReviewDate(Date tmsReviewDate) {
		this.tmsReviewDate = tmsReviewDate;
	}

	public boolean isTmsReviewBlurry() {
		return this.tmsReviewBlurry;
	}

	public void setTmsReviewBlurry(boolean tmsReviewBlurry) {
		this.tmsReviewBlurry = tmsReviewBlurry;
	}

	public boolean isTmsReviewDark() {
		return this.tmsReviewDark;
	}

	public void setTmsReviewDark(boolean tmsReviewDark) {
		this.tmsReviewDark = tmsReviewDark;
	}

	public boolean isTmsReviewLogo() {
		return this.tmsReviewLogo;
	}

	public void setTmsReviewLogo(boolean tmsReviewLogo) {
		this.tmsReviewLogo = tmsReviewLogo;
	}

	public boolean isTmsReviewOther() {
		return this.tmsReviewOther;
	}

	public void setTmsReviewOther(boolean tmsReviewOther) {
		this.tmsReviewOther = tmsReviewOther;
	}

	public boolean isTmsReviewUnsure() {
		return this.tmsReviewUnsure;
	}

	public void setTmsReviewUnsure(boolean tmsReviewUnsure) {
		this.tmsReviewUnsure = tmsReviewUnsure;
	}

	public boolean isTmsPriority() {
		return this.tmsPriority;
	}

	public void setTmsPriority(boolean tmsPriority) {
		this.tmsPriority = tmsPriority;
	}

}
