// default package
// Generated 19-giu-2015 16.47.19 by Hibernate Tools 3.4.0.CR1
package main.webapp.ecsa.hibernate;
/**
 * TvserieUserId generated by hbm2java
 */
public class TvserieUserId implements java.io.Serializable {

	private int id;
	private int user;
	private String tvserie;

	public TvserieUserId() {
	}

	public TvserieUserId(int id, int user, String tvserie) {
		this.id = id;
		this.user = user;
		this.tvserie = tvserie;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getUser() {
		return this.user;
	}

	public void setUser(int user) {
		this.user = user;
	}

	public String getTvserie() {
		return this.tvserie;
	}

	public void setTvserie(String tvserie) {
		this.tvserie = tvserie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TvserieUserId))
			return false;
		TvserieUserId castOther = (TvserieUserId) other;

		return (this.getId() == castOther.getId())
				&& (this.getUser() == castOther.getUser())
				&& ((this.getTvserie() == castOther.getTvserie()) || (this
						.getTvserie() != null && castOther.getTvserie() != null && this
						.getTvserie().equals(castOther.getTvserie())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getUser();
		result = 37 * result
				+ (getTvserie() == null ? 0 : this.getTvserie().hashCode());
		return result;
	}

}
