// default package
// Generated 19-giu-2015 16.47.19 by Hibernate Tools 3.4.0.CR1
package main.webapp.ecsa.hibernate;
/**
 * TvserieUser generated by hbm2java
 */
public class TvserieUser implements java.io.Serializable {

	private TvserieUserId id;

	public TvserieUser() {
	}

	public TvserieUser(TvserieUserId id) {
		this.id = id;
	}

	public TvserieUserId getId() {
		return this.id;
	}

	public void setId(TvserieUserId id) {
		this.id = id;
	}

}
