// default package
// Generated 19-giu-2015 16.47.19 by Hibernate Tools 3.4.0.CR1
package main.webapp.ecsa.hibernate;
/**
 * Userserie generated by hbm2java
 */
public class Userserie implements java.io.Serializable {

	private UserserieId id;

	public Userserie() {
	}

	public Userserie(UserserieId id) {
		this.id = id;
	}

	public UserserieId getId() {
		return this.id;
	}

	public void setId(UserserieId id) {
		this.id = id;
	}

}
