// default package
// Generated 19-giu-2015 16.47.19 by Hibernate Tools 3.4.0.CR1
package main.webapp.ecsa.hibernate;
/**
 * UserserieId generated by hbm2java
 */
public class UserserieId implements java.io.Serializable {

	private int id;
	private int serie;
	private String user;

	public UserserieId() {
	}

	public UserserieId(int id, int serie, String user) {
		this.id = id;
		this.serie = serie;
		this.user = user;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getSerie() {
		return this.serie;
	}

	public void setSerie(int serie) {
		this.serie = serie;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserserieId))
			return false;
		UserserieId castOther = (UserserieId) other;

		return (this.getId() == castOther.getId())
				&& (this.getSerie() == castOther.getSerie())
				&& ((this.getUser() == castOther.getUser()) || (this.getUser() != null
						&& castOther.getUser() != null && this.getUser()
						.equals(castOther.getUser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getSerie();
		result = 37 * result
				+ (getUser() == null ? 0 : this.getUser().hashCode());
		return result;
	}

}
